const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const q=require('../data/questions'),legacy=require('../legacy/questions-v1'),engine=require('../services/quiz-engine'),cards=require('../services/card-engine'),themes=require('../data/share-themes'),storage=require('../services/storage');
test('all 160 contextual questions have five unique no-first-person answers and explicit balanced scoring',()=>{for(const item of q){assert.equal(item.version,2);assert.ok(item.text.length>0&&item.text.endsWith('？'));assert.equal(item.options.length,5);assert.equal(new Set(item.options.map(x=>x.id)).size,5);assert.equal(new Set(item.options.map(x=>x.text)).size,5);assert.deepEqual(item.options.map(x=>x.score),[-2,-1,0,1,2].map(x=>x===0?0:x*item.polarity));for(const o of item.options)assert.ok(o.text&&!o.text.includes('我'));assert.ok(fs.existsSync(path.join(__dirname,'..','assets/nordic',item.illustrationId+'.jpg')))}});
test('replacement preserves mode, direction quotas and other answers; pause restores new question',()=>{storage.clear();const session=engine.create(24);session.answers[1]='o2';const before=engine.get(session.ids[0],2),next=engine.replace(session,[],()=>0),after=engine.get(next.ids[0],2);assert.notEqual(before.id,after.id);assert.equal(before.dimension,after.dimension);assert.equal(before.polarity,after.polarity);assert.equal(next.answers[0],null);assert.equal(next.answers[1],'o2');assert.equal(new Set(next.ids).size,24);storage.update(d=>{d.quiz=next});assert.deepEqual(storage.read().quiz,next)});
test('legacy ongoing quizzes retain original questions, answer meaning and deterministic scores',()=>{const dims=['EI','SN','TF','JP'];const ids=dims.flatMap(dim=>legacy.filter(x=>x.dimension===dim).slice(0,6).map(x=>x.id));const session={version:1,mode:24,ids,answers:ids.map(()=>4),index:5};assert.ok(engine.valid(session));assert.equal(engine.get(ids[0],1).text,legacy.find(x=>x.id===ids[0]).text);assert.ok(engine.get(ids[0],1).options[0].text.includes('不同意'));assert.deepEqual(engine.score(ids,ids.map(()=>4),1),engine.score(ids,ids.map(()=>'o4'),1));assert.throws(()=>engine.replace(session))});
test('24 fortune card faces cycle across days without repeats; 32 personality faces are type-specific',()=>{const state=storage.empty();const picked=[];for(let i=0;i<24;i++){state.daily={day:'day-'+i};const selection=cards.pick(state,'fortune',null,()=>.2);picked.push(selection.templateId);cards.reserve(state,selection)}assert.equal(new Set(picked).size,24);const next=cards.pick(state,'fortune',null,()=>.2);assert.notEqual(next.templateId,picked.at(-1));for(const type of new Set(themes.filter(t=>t.kind==='profile').map(t=>t.type))){const a=cards.pick(state,'profile',type,()=>.2);cards.reserve(state,a);const b=cards.pick(state,'profile',type,()=>.2);assert.notEqual(a.templateId,b.templateId);assert.ok(b.templateId.startsWith(type))}});
test('56 independent card images exist with distinct bytes; every image stays under 200 KB',()=>{const hashes=new Set();for(const t of themes){const file=path.join(__dirname,'..',t.artPath),data=fs.readFileSync(file);assert.ok(data.length<200*1024);hashes.add(crypto.createHash('sha256').update(data).digest('hex'))}assert.equal(hashes.size,56)});
test('sourced international quotations retain author, work, self-translation and source evidence',()=>{const fortunes=require('../data/fortunes'),proof=require('./quote-proof.json');assert.ok(proof.length>=8);for(const evidence of proof){const entry=fortunes.find(x=>x.id===evidence.id);assert.equal(entry.source.original,evidence.original);assert.ok(entry.source.author&&entry.source.work);assert.equal(entry.source.translation,'本项目自译');assert.match(entry.source.url,/github.com\/GITenberg\//);assert.equal(evidence.sha256.length,64)}});
test('old fortune histories retain original text while new links carry explicit version',()=>{const content=require('../services/content'),old=require('../legacy/fortune-texts-v1'),current=require('../data/fortunes');const id=current[0].id;assert.equal(content.getFortune(id,1).mainText,old[id].mainText);assert.equal(content.getFortune(id,2).mainText,current[0].mainText);assert.notEqual(content.getFortune(id,1).mainText,content.getFortune(id,2).mainText)});
