const questions=require('../data/questions'),legacy=require('../legacy/questions-v1');
const DIMS=['EI','SN','TF','JP'];
function bank(version=2){return version===1?legacy:questions;}
function shuffle(list,rng=Math.random){const a=list.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function select(mode,recent=[],rng=Math.random){if(![24,60].includes(mode))throw Error('无效题数');const seen=new Set(recent);let fallback=false;const queues=DIMS.map((dim,i)=>{const positive=mode===24?3:(i%2===0?8:7),negative=mode/4-positive;let out=[];[[1,positive],[-1,negative]].forEach(([pol,n])=>{const pool=questions.filter(q=>q.dimension===dim&&q.polarity===pol),fresh=shuffle(pool.filter(q=>!seen.has(q.id)),rng),old=shuffle(pool.filter(q=>seen.has(q.id)),rng);if(fresh.length<n)fallback=true;out=out.concat(fresh.concat(old).slice(0,n));});return shuffle(out,rng);});const ids=[];for(let round=0;round<mode/4;round++)shuffle([0,1,2,3],rng).forEach(i=>ids.push(queues[i][round].id));return {ids,fallback};}
function get(id,version){const v=version||(id.startsWith('v2-')?2:1),q=bank(v).find(x=>x.id===id);if(!q)return null;if(v===2)return q;return {...q,illustrationId:'quiz-07',options:['非常不同意','不同意','一般','同意','非常同意'].map((text,i)=>({id:'o'+(i+1),text,score:q.polarity*(i-2)}))};}
function option(q,answer){return typeof answer==='number'?q.options[answer-1]:q.options.find(x=>x.id===answer);}
function score(ids,answers,version){if(ids.length!==answers.length||!ids.length||new Set(ids).size!==ids.length)throw Error('答题数据不完整');const sums={},counts={};DIMS.forEach(d=>{sums[d]=0;counts[d]=0});ids.forEach((id,i)=>{const q=get(id,version),a=q&&option(q,answers[i]);if(!a)throw Error('无效回答');sums[q.dimension]+=a.score;counts[q.dimension]++;});let type='';const dimensions=DIMS.map(d=>{if(!counts[d])throw Error('缺少维度');const value=Math.round(sums[d]/(2*counts[d])*100);type+=value>=0?d[0]:d[1];return {dimension:d,value,firstPercent:Math.round((value+100)/2),balanced:Math.abs(value)<15,tie:value===0};});return {type,dimensions};}
function create(mode,recent){const chosen=select(mode,recent);return {version:2,mode,ids:chosen.ids,answers:chosen.ids.map(()=>null),index:0,startedAt:Date.now(),fallback:chosen.fallback,replaced:[]};}
function valid(q){return !!q&&[1,2].includes(q.version)&&[24,60].includes(q.mode)&&Array.isArray(q.ids)&&q.ids.length===q.mode&&new Set(q.ids).size===q.mode&&q.ids.every(id=>get(id,q.version))&&Array.isArray(q.answers)&&q.answers.length===q.mode&&q.answers.every((a,i)=>a===null||!!option(get(q.ids[i],q.version),a))&&Number.isInteger(q.index)&&q.index>=0&&q.index<q.mode;}
function replace(session,recent=[],rng=Math.random){if(!valid(session)||session.version!==2)throw Error('旧版进度请继续完成或重新开始');const current=get(session.ids[session.index],2),used=new Set(session.ids.concat(session.replaced||[]));const all=questions.filter(q=>q.dimension===current.dimension&&q.polarity===current.polarity&&!used.has(q.id));const fresh=all.filter(q=>!recent.includes(q.id)),pool=fresh.length?fresh:all;if(!pool.length)throw Error('这个方向的可替换题已用完，请尝试其他题目或重新开始');const next=JSON.parse(JSON.stringify(session));next.replaced=(next.replaced||[]).concat(current.id);next.ids[next.index]=pool[Math.floor(rng()*pool.length)].id;next.answers[next.index]=null;return next;}
module.exports={select,score,create,valid,replace,get,option,DIMS};
